version: '3.8'

services:
  frontend:
    image: bhoomiguptaa/frontend-app:v1  # Your Jenkins-built image
    ports:
      - "3000:3000"
    networks:
      - netfrontend
    depends_on:
      - backend

  backend:
    image: bhoomiguptaa/backend-app:v1  # Your Jenkins-built image
    ports:
      - "5000:5000"
    networks:
      - netfrontend
      - netbackend
    depends_on:
      - db

  redis:
    image: redis:alpine
    networks:
      - netbackend

  db:
    image: mongo:latest
    networks:
      - netbackend

networks:
  netfrontend:
  netbackend:
